version: "3.9"

services:
  postgres:
    image: bitnami/postgresql:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DATABASE=threewygo
    ports:
      - "5432:5432"

volumes:
  postgres_data: {}
  redis_data: {}
